apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-app-web-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: exam-app-web
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: exam-app-web
    spec:
      containers:
      - name: web-cont
        image: %IMAGE-NAME%:%IMAGE-TAG%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: web-host
  labels:
    app: exam-app-web-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: exam-app-web
---
apiVersion: v1
kind: Pod
metadata:
  name: exam-app-db
  labels:
    app: exam-app-db
spec:
  containers:
  - name: db-cont
    image: redis
    ports:
    - containerPort: 6379 
---
apiVersion: v1
kind: Service
metadata:
  name: db-host
  labels:
    app: exam-app-db-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: exam-app-db